function [nu_T] = compute_nu_T(Ur,Uth, ...
                               ur_ur,ur_uth,uZ_ur, ...
                               uth_uth ,uth_uz,uZ_uZ, ...
                               dUr_dr,dUth_dr,dUZ_dr, ...
                               dUr_dz,dUth_dz,dUZ_dz, ...
                               R)

    nu_T_num(:,:) = ((ur_ur).*(R.*R).*dUr_dr) ...
                  + ((ur_uth).*((R.*R).*dUth_dr - (R.*Uth))) ...
                  + ((R.*R).*(uZ_ur).*(dUr_dz + dUZ_dr)) ...
                  + ((uth_uth).*(R.*Ur)) ...
                  + ((R.*R).*(uth_uz).*(dUth_dz)) ...
                  + ((uZ_uZ).*(R.*R).*(dUZ_dz));
    nu_T_denom(:,:) = 2*((R.*dUr_dr).^2 ...
                       + (R.*dUth_dr -Uth).^2 ...
                       + (R.*(dUr_dz + dUZ_dr)).^2 ...
                       + (Ur.*Ur).^2 ...
                       + (R.*dUth_dz).^2 ...
                       + (R.*dUZ_dz).^2);
    nu_T = nu_T_num./nu_T_denom;
end